title: Yuanyuan Yao's Homepage
page-top-title: Yuanyuan Yao
top-section-bg-text: Computer Science
home-subtitle: Yuanyuan Yao&enfj;|&enfj;姚媛媛
copyright-text: '&copy; Yuanyuan Yao 2025-2026. All Rights Reserved.'
