title: Yuanyuan Yao's Homepage
page-top-title: Yuanyuan Yao
top-section-bg-text: Let Time Speak, Let Data Decide.
home-subtitle: Yuanyuan Yao
copyright-text: '&copy; Yuanyuan Yao 2025-2026. All Rights Reserved.'
